---
kind: pipeline
type: docker
name: casper-blockexplorer-middleware

steps:
  - name: install
    image: casperlabs/node-build-u1804
    commands:
      - make middleware-ci-install

  - name: audit
    image: casperlabs/node-build-u1804
    commands:
      - make middleware-audit

  - name: lint
    image: casperlabs/node-build-u1804
    commands:
      - make middleware-lint

  - name: npm test
    image: casperlabs/node-build-u1804
    environment:
      NODE_URLS: 'https://rpc.testnet.casperlabs.io/rpc'
    commands:
      - make middleware-test

trigger:
  branch:
    - dev
    - "feat-*"
    - "release-*"
  event:
    include:
      - pull_request
      - push
    exclude:
      - tag
      - cron

---
kind: pipeline
type: docker
name: nightly-testing

steps:
  - name: npm install
    image: casperlabs/node-build-u1804
    commands:
      - make middleware-ci-install

  - name: npm test
    image: casperlabs/node-build-u1804
    environment:
      NODE_URLS: 'https://rpc.testnet.casperlabs.io/rpc'
    commands:
      - make middleware-test

  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_nightly
      template:
        - |
          Casper-Blockexplorer-Middleware Nightly Test Status: *{{ uppercasefirst build.status }}*
          Repo: {{ repo.name }}
          Author: {{ build.author }}
          Drone Build: <{{ build.link }}|#{{ build.number }}>
          Commit Link: <https://github.com/{{repo.owner}}/{{repo.name}}/commit/{{build.commit}}|{{ truncate build.commit 10 }}>
    when:
      status:
        - failure
        - success

trigger:
  cron: [nightly-tests-cron]
