version: "3.9"
services:
  casper-blockexplorer-middleware-cicd:
    image: casper-blockexplorer-middleware-cicd
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_URLS=https://rpc.mainnet.casperlabs.io/rpc
    ports:
      - "4000:4000"
