version: "3.9"
services:
  casper-blockexplorer-middleware-cicd:
    image: casper-blockexplorer-middleware-cicd
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_URLS=http://3.138.177.248:7777/rpc
    ports:
      - "4000:4000"