apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.appName}}-{{.Values.envName}}-config
  namespace: {{.Values.namespace}}
data:
  NODE_URLS: {{.Values.nodeUrls}}
  PORT: {{.Values.containerPort}}
  PEERS_UPDATE_INTERVAL: {{.Values.peersUpdateInterval}}
  COIN_GECKO_PUBLIC_API_URL: {{.Values.coinGeckoPublicApiUrl}}


